### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by AshrafAbuBakr**
I recommend you'd test it also to make sure things are fine.

### CODE REVIEW

**Comment by FabrizioBrancati** [comment]
Thanks! But can you sync it with master?

**Comment by FabrizioBrancati** [comment]
Once I've tested it, I'll merge!

**Comment by AshrafAbuBakr** [comment]
Ok
If you find any problems just tell me.

**Comment by FabrizioBrancati** [comment]
The `LimitedTextFieldDelegate` doesn't work, if I want to use the other delegate methods I can't.
We have to create a `BFTextField` subclass of `UITextField`, define a `BFTextFieldDelegate` that extends the `UITextFieldDelegate` with the `maxCharacter` property and related methods.

**Comment by AshrafAbuBakr** [comment]
Yeah you’re right.
I’ll make it a subclass.
Did you face any other problems?

**Comment by FabrizioBrancati** [comment]
Sincerly I didn't try the other things, but I've seen that a NSString+BFKit.m.orig and .h.orig has been created, maybe there was conflict.

**Comment by AshrafAbuBakr** [comment]
I've added BFTextfield as we discussed.
Please check and pull it.
Thank You.

**Comment by FabrizioBrancati** [comment]
I've test it and something doesn't work, but I'll merge and I'll fix it, don't worry :+1: 
Thanks!

**Comment by AshrafAbuBakr** [comment]
May I know what was the problem?

**Comment by FabrizioBrancati** [comment]
Yes, sorry if I didn't say it to you before.
The main problem was that you has defined the BFTextFieldDelegate with `@interface`, but delegates aka protocols has to be defined with `@protocols`.
The other little problems was that you left somethings in other files, like unused variables, that I've removed.
Maybe I've found another method to limit the characters without delegates.
Let me try and see the next commit!

**Comment by AshrafAbuBakr** [comment]
Ok
Sorry I was very busy I haven't tested it enough.

**Comment by FabrizioBrancati** [comment]
Don't worry :wink:

**Pull request merged**
