### PR TITLE
Add Traditional Chinese (zh-TW) Localization

### PR DESCRIPTION
**Pull request by simonlinj**

### CODE REVIEW

**Comment by FabrizioBrancati** [comment]
Sorry, but what's the difference between this localization and the other Chinese localization that BFKit already have?

**Comment by simonlinj** [comment]
some characters are slightly different

eg: 
继续 <-> 繼續
错误 <-> 錯誤
zh-Hans  Simplified Chinese (used in China)
zh-TW Traditional Chinese (used in Taiwan)

**Comment by simonlinj** [comment]
ups but I made a mistake. the filename should be zh-Hant instead

**Comment by FabrizioBrancati** [comment]
Ok! Thanks :+1:

**Pull request merged**
