### PR TITLE
Hexadecimal manipulations methods

### PR DESCRIPTION
**Pull request by fabiosoft**
Added some useful methods to manipulate string and data in HEX format.

### CODE REVIEW

**Comment by FabrizioBrancati** [comment]
I don't like the method ```removeExtraSpaces```.
Why not merge this into ```stringFromHEXString```?
I mean something like ```stringFromHEXString:removeExtraSpaces:``` with a BOOL as parameter and ```stringFromHEXString``` that calls ```stringFromHEXString:removeExtraSpaces:``` with ```NO```.

At last can you provide a method that from a NSString returns the NSData?
The method can be something like ```HEXData``` in NSString category :smile: 

Don't hate me ahah

**Comment by fabiosoft** [comment]
Consider the following example:
```
"    Hello      this  is a   long       string!   "
```
I want to convert that to:
```
"Hello this is a long string!"
```
i can just make 
```obj-c
noSpacedStr = [spacedStr removeExtraSpaces];
```
This method could not be related to HEX at all...

For sure i can work on HEXData method... what should it returns?

**Comment by FabrizioBrancati** [comment]
I think that ```[squashed stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]``` will remove every space in the string.
And I don't know why you remove all occurences of ```[ ]+``` with a blank space.

However HEXData can be a method in NSString category that returns an NSData, so you convert HEX NSData to a NSString and returns to a NSData.

**Comment by fabiosoft** [comment]
No, it's wrong... `[squashed stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]` removes only spaces from left or right, but if extra space is in the middle of the string it left them as is.
For this reason i used a regex to catch them all.

Please merge this while i work to `HEXData` method.

**Comment by FabrizioBrancati** [comment]
Sorry I didn't read the line ```options:NSRegularExpressionSearch``` in ```removeExtraSpace``` method.
So this is a Regex, but does't miss ```/g``` (```/g``` is for ```global``` in regex)?
I can't try this at the moment, and I don't know if this Regex remove only the first extra space or all the extra spaces.
Anyway I'll merge this when you provide a ```HEXData``` method, so you can convert NSString to HEX and viceversa.

Thanks!

**Comment by fabiosoft** [comment]
Like this?

**Comment by FabrizioBrancati** [comment]
I can't try it at the moment, but if with this function you can do HEXData->HEXString and then HEXString->HEXData and it returns the same original data, the answer is yes, otherwise, no.

**Comment by fabiosoft** [comment]
YES, it return th NSData. 
Please merge

**Comment by FabrizioBrancati** [comment]
Look, I tried your code.
This was my test:
```objective-c
NSString *testString = @"This is a test";
BFLog(testString);
NSData *testData = [testString HEXData];
BFLog(@"%@", testData);
testString = [testData HEXstring];
BFLog(testString);
testData = [testString HEXData];
BFLog(@"%@", testData);
    
testString = @"68 65 6c 6c 6f";
BFLog(testString);
testString = [testString stringFromHEXstring];
BFLog(testString);
testData = [testString HEXData];
BFLog(@"%@", testData);
testString = @"68 65 6c 6c 6f";
BFLog(testString);
testData = [testString HEXData];
BFLog(@"%@", testData);
testString = [testData HEXstring];
BFLog(testString);
testString = @"This    is    a     test";
BFLog(testString);
testString = [testString removeExtraSpaces];
BFLog(testString);
```
And this was the result:
```
This is a test
<0a>
0a 
<0a>

68 65 6c 6c 6f
hello
<>
68 65 6c 6c 6f
<68656c6c 6f>
68 65 6c 6c 6f 
This    is    a     test
This is a test
```

Now, the only methods that seem works are: ```removeExtraSpaces``` and ```stringFromHEXstring```.
For me, this is what ```HEXData``` and ```HEXString``` must do:
```HEXData```: From a NSString like ```@"Hello"```, returns the NSData of the string, ```68 65 6c 6c 6f```.
```HEXString```: From a NSData like ```68 65 6c 6c 6f```, returns the NSString of the data, ```Hello```.
With this 2 methods you can now do: ```HEXData```->```HEXString```->```HEXData```->```HEXString``` and the data will never change.

**Comment by fabiosoft** [comment]
Now should be more clear

**Comment by FabrizioBrancati** [comment]
This is not what I wanted, but it's ok.
Update your repo and I'll merge it! :+1:

**Comment by fabiosoft** [comment]
Done.

**Comment by FabrizioBrancati** [comment]
Sorry for delay, you can do it in swift?

**Pull request merged**
